name: Build
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  build-project:
    name: Build Project
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2

      - name: Install boost
        uses: MarkusJx/install-boost@v2.4.5
        id: install-boost
        with:
            # REQUIRED: Specify the required boost version
            # A list of supported versions can be found here:
            # https://github.com/MarkusJx/prebuilt-boost/blob/main/versions-manifest.json
            boost_version: 1.84.0
            # OPTIONAL: Specify a platform version
            platform_version: 22.04
            # OPTIONAL: Specify a custom install location
            boost_install_dir: /home/runner/.local
            # OPTIONAL: Specify a toolset
            toolset: gcc
            # OPTIONAL: Specify an architecture
            arch: x86
              
      - name: Configure Project
        uses: threeal/cmake-action@v1.3.0
        env:
            BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}
      - name: Build Project
        run: cmake --build build --config Release

      - name: Install Project
        run: cmake --install build --prefix install

      - name: Upload Project as Artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: package-${{ matrix.os }}
          path: install